title: digital-work lab
description: The digital-work lab handbook
theme: just-the-docs

baseurl: "/handbook"
url: "https://digital-work-lab.github.io"

repository: digital-work-lab/handbook

gh_edit_link: true
gh_edit_link_text: 'Help improve this page'
gh_edit_repository: 'https://github.com/digital-work-lab/handbook'
gh_edit_branch: 'main'
gh_edit_view_mode: 'tree'

search:
    focus_shortcut_key: 'k'

mermaid:
  version: "11.1.0"

plugins:
  - "jekyll-github-metadata"
  - "jekyll-redirect-from"

enable_copy_code_button: true

logo: "/assets/images/digital-work-lab.png"

callouts:
  important:
    title: Important
    color: red
  warning:
    title: Warning
    color: red
  confidential:
    title: Confidential data
    color: red
  highlight:
    color: yellow
  info:
    title: Info
    color: yellow
  objective:
    title: Learning objective
    color: blue

collections:
  projects:
    sort_by: status
    output: true
    permalink: /docs/20-research/25-projects/:name.html

  courses:
    output: true
    sort_by: semester
    permalink: /docs/30-teaching/32_courses/:name.html

aux_links:
  "Website":
    - "https://www.uni-bamberg.de/digital-work/"
  "Repository":
    - "https://github.com/digital-work-lab/handbook"
  "Improvement":
    - "https://github.com/digital-work-lab/handbook/issues"
