filename: regex(r'^20\d{2}-(WiSe|SoSe)-(IDW|OSP|LRSem|EidWI)\.md$')
layout: str(equals='default')
title: regex(r'(IDW|OSP|LRSem|EidWI)')
title_long: str()
parent: str(equals="32 Courses")
grand_parent: str(equals="Teaching")
semester: regex(r'^20\d{2}-(WiSe|SoSe)$')
status: str()
student_evaluations: str()
improvement_issue: str()
improvement_status: str()